version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12345676
  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
